_target_: src.models.lstur.lstur_module.LSTURModule

# training strategy
supcon_loss: False
late_fusion: False
temperature: 0.1

# news encoder
dataset_attributes: ['title', 'category', 'subcategory']
pretrained_word_embeddings_path: ${paths.data_dir}MIND${datamodule.size}_train/pretrained_word_embeddings.npy
word_embedding_dim: ${datamodule.word_embedding_dim}
num_categories: 304
num_filters: 300
window_size: 3
query_vector_dim: 200
dropout_probability: 0.2

# user encoder 
num_users: 643372
user_masking_probability: 0.5
long_short_term_method: 'ini' # ini, con

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
